// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pedgzjryhhnzitmkhdsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlZGd6anJ5aGhueml0bWtoZHNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNTczNTksImV4cCI6MjA2NDgzMzM1OX0.CNLHuyYVSkl6_KFjXzfZH3txgHJiHVwLnVUWFOR773E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);